trigger:
  branches:
    include:
      - releases/*
  paths:
    include:
      - TapToPayExperiment/MobileApp

pool:
  vmImage: ubuntu-latest

jobs:
  - job: deploy_android
    displayName: Deploy Android
    steps:
      - checkout: self

      - script: |
          git fetch --all
          git switch releases/$(Build.SourceBranchName)
        displayName: "Checkout release branch"

      - task: UseNode@1
        inputs:
          version: "20.x"

      - script: npm ci --legacy-peer-deps
        workingDirectory: TapToPayExperiment/MobileApp
        displayName: "Install npm dependencies"

      - script: npm run prebuild -- --no-install --platform android
        workingDirectory: TapToPayExperiment/MobileApp
        displayName: "Prebuild Android project"

      - task: JavaToolInstaller@0
        inputs:
          versionSpec: "11"
          jdkArchitectureOption: "x64"
          jdkSourceOption: "PreInstalled"

      - task: UseRubyVersion@0
        inputs:
          versionSpec: "3.x"

      - script: bundle install
        workingDirectory: TapToPayExperiment/MobileApp/android
        displayName: "Install fastlane gems"

      - bash: ci/scripts/import-play-credentials.sh
        workingDirectory: TapToPayExperiment/MobileApp
        displayName: "Import Play credentials"
        env:
          PLAY_CREDENTIALS: $(PLAY_CREDENTIALS_SECRET)

      - bash: ci/scripts/import-keystores.sh
        workingDirectory: TapToPayExperiment/MobileApp
        displayName: "Import keystores"
        env:
          KEYSTORE_DATA: $(KEYSTORE_DATA_SECRET)

      - script: bundle exec fastlane deploy
        workingDirectory: TapToPayExperiment/MobileApp/android
        displayName: "Upload app to Google Play"
        env:
          KEYSTORE_PATH: $(Build.SourcesDirectory)/TapToPayExperiment/MobileApp/android/app
          KEYSTORE_KEY_ALIAS: $(KEYSTORE_KEY_ALIAS_SECRET)
          KEYSTORE_KEY_PASSWORD: $(KEYSTORE_KEY_PASSWORD_SECRET)
          KEYSTORE_STORE_PASSWORD: $(KEYSTORE_STORE_PASSWORD_SECRET)
