trigger:
  branches:
    include:
    - releases/*
  paths:
    include:
    - TapToPayExperiment/MobileApp

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
  - repository: githubrepo
    type: github
    endpoint: klcantrell (2)
    name: klcantrell/krx
    ref: releases/$(Build.SourceBranchName)

jobs:
- job: deploy_iOS
  displayName: Deploy iOS
  steps:
  - checkout: githubrepo

  - task: UseNode@1
    inputs:
      version: '20.x'
    displayName: 'Install Node.js'

  - script: ls
    displayName: 'Check working directory'
