trigger:
  branches:
    include:
      - releases/*
  paths:
    include:
      - TapToPayExperiment/MobileApp

pool:
  vmImage: ubuntu-latest

jobs:
  - job: deploy_iOS
    displayName: Deploy iOS
    steps:
      - checkout: self

      - script: |
          git fetch --all
          git switch releases/$(Build.SourceBranchName)
        displayName: "Checkout release branch"

      - task: UseNode@1
        inputs:
          version: "20.x"
        displayName: "Install Node.js"

      - script: npm ci --legacy-peer-deps
        workingDirectory: TapToPayExperiment/MobileApp
        displayName: "Install npm dependencies"

      - script: npm run prebuild -- --no-install --platform ios
        workingDirectory: TapToPayExperiment/MobileApp/ios
        displayName: "Prebuild iOS project"

      - script: bundle install
        workingDirectory: TapToPayExperiment/MobileApp/ios
        displayName: "Install fastlane gems"
