trigger:
  branches:
    include:
      - releases/*
  paths:
    include:
      - TapToPayExperiment/MobileApp

pool:
  vmImage: macOS-13

jobs:
  - job: deploy_iOS
    displayName: Deploy iOS
    steps:
      - checkout: self
        persistCredentials: true
        clean: true

      - script: |
          git fetch --all
          git switch releases/$(Build.SourceBranchName)
        displayName: "Checkout release branch"

      - task: UseNode@1
        inputs:
          version: "20.x"

      - script: npm ci --legacy-peer-deps
        workingDirectory: TapToPayExperiment/MobileApp
        displayName: "Install npm dependencies"

      - script: npm run prebuild -- --no-install --platform ios
        workingDirectory: TapToPayExperiment/MobileApp
        displayName: "Prebuild iOS project"

      - script: pod install
        workingDirectory: TapToPayExperiment/MobileApp/ios
        displayName: "Install Pods"

      - task: UseRubyVersion@0
        inputs:
          versionSpec: "3.x"

      - script: bundle install
        workingDirectory: TapToPayExperiment/MobileApp/ios
        displayName: "Install fastlane gems"

      - bash: ci/scripts/import-certificates.sh
        workingDirectory: TapToPayExperiment/MobileApp
        displayName: "Import signing certificates"
        env:
          IOS_DIST_SIGNING_KEY: $(IOS_DIST_SIGNING_KEY_SECRET)
          IOS_DIST_SIGNING_KEY_PASSWORD: $(IOS_DIST_SIGNING_KEY_PASSWORD_SECRET)

      - bash: ci/scripts/import-profiles.sh
        workingDirectory: TapToPayExperiment/MobileApp
        displayName: "Import provisioning profiles"
        env:
          PROVISIONING_PROFILE_DATA: $(PROVISIONING_PROFILE_DATA_SECRET)

      - script: bundle exec fastlane deploy
        workingDirectory: TapToPayExperiment/MobileApp/ios
        displayName: "Upload app to Test Flight"
        env:
          ASC_APPLE_ID: $(ASC_APPLE_ID_SECRET)
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: $(APPLE_APP_SPECIFIC_PASSWORD_SECRET)

      - script: |
          git config --global user.email "cantrellkalalau@gmail.com"
          git config --global user.name "runner"
          git restore .
          git reset --hard
          git checkout main
          npm run bumpVersions -- ios
          git add versions.json
          git commit -m "[TapToPayExperiment] Bump iOS version" -m "[skip ci]"
          git pull --rebase
          git push
        workingDirectory: TapToPayExperiment/MobileApp
        displayName: "Bump version"
