trigger:
  branches:
    include:
    - releases/*
  paths:
    include:
    - TapToPayExperiment/MobileApp

pool:
  vmImage: ubuntu-latest

jobs:
- job: deploy_iOS
  displayName: Deploy iOS
  steps:
  - checkout: self@releases/$(Build.SourceBranchName)

  - task: UseNode@1
    inputs:
      version: '20.x'
    displayName: 'Install Node.js'

  - script: ls
    displayName: 'Check working directory'
